### ISSUE TITLE
Write detailled specifications on the errors returned

### ISSUE THREAD

**Issue by ouvrierl** [populse/populse_db#10]
How should we manage the errors in populse_db?

For now I do not check the parameters, so it's most of the time SQLAlchemy errors that occur if there is a problem.

Should we leave it like this? Should we create our errors? Should we check every parameter at the beginning of the functions (What I did at the beginning)? In this case, what do we return?

**Comment by ouvrierl** [comment]
After talking with Eric, we decided to return different values, depending on the problem.

**Comment by servoz** [comment]
there are two ways (at least !!!).
Exception from API <---> try /catch by the user of the API
or 
return code from API <----> gestion of the code by the user of the API

I am may be wrong but I think that in the two cases, the user of the API have to manage previously the case (by coding in the script), for  when the exception or the return code is catched.

Exception / try / catch can be considered as more elegant ... and the try / catch is clearly pythonic ("It’s easier to ask for forgiveness than permission” (EAFP)" ... So, ok for me, for exception/try/catch
