### ISSUE TITLE
Ability to query on list tags

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#17]
We have the possibility to store tags of type `list_*`. But the management of these tags is complicated for retrieving values and for querying using list elements. For instance, it is not yet possible to retrieve all paths having a given value in a list tag. We must find a way to do the following things on list tags :

1. Insert/remove tag :+1: 
1. Insert/remove values :+1: 
1. Select paths using equality on a given Python list :-1:
1. Select paths using list tags containing a given Python value :-1: 
1. Select paths using list tags containing at least one of the elements of  a given Python list :-1: 
1. Select paths using list tags containing at least all elements of  a given Python list :-1: 
1. Save/load queries on files or databases :-1: 

I used :+1: when the feature is already working and :-1: otherwise

**Comment by sapetnioc** [comment]
To do some experiments, I created a list branch that completely changed the internal implementation of lists. It does not use separate tables for storing list values for a tag but directly store the list as a Python value in a sting column. I created a custom SqlAlchemy column type for list elements so that storing/retrieval of values is handled automatically. This implementation is far from perfection but provides the equality selection feature (feature number 3).

**Comment by ouvrierl** [comment]
Hi,
I spent a lot of time since yesterday, in order to find a new schema for the database.
I was able to find a solution with only 2 tables: tag and path.
I currently store the str representation of the lists, and I recreate the list at output thanks to ast module.
This schema is way faster since I can import 1000 paths in 7 seconds now (it was 40 seconds with the old schema).
I put the new schema on master, I hope it's not a bad idea.
I have to see with David and Eric what we really want for the list searches, and will focus on it as soon as we have the precise specifications.

**Comment by sapetnioc** [comment]
Well, I have the feeling that it is the same idea as what I did on list branch (I did not look at your code yet). I also used ast to securely build Python list from string. We will look at each-other implementations and took the better of both.

I did this change in the quest for a selection extension for lists. But I am afraid that we cannot do all the selection we need at the SQL level. It would be possible in PostgreSQL but not in SQLite. Therefore I think we will not be able to only rely on SqlAlchemy for our query language. On SQlite implementation we will have to separate list tags from simple tags and then select on simple tags with SQL and then select on list tags in Python. I will try to propose something for selection syntax for tomorrow.

**Comment by servoz** [comment]
can we think (and hope !) that the solution for the case #3 (Select paths using equality on a given Python list) open the way for the 2 following ? (in a nutshell, if it is possible for a value, il will be possible to loop on a list to work finally on a value ? may be too dirty ???)

**Comment by ouvrierl** [comment]
The filter is a single query now, I did it yesterday.
At the end it's a big filter, with a lot of conditions linked by and and or operators.
If we write custom operators for the lists, we should be fine right?

**Comment by sapetnioc** [comment]
I am not yet an expert on custom operators so I may be wrong but I think they can only produce SQL selection code at the end but not Python selection code. Otherwise it would not be possible to combine them. For instance, how SqlAlchemy could implement a query with the structure `(SQL selection OR Python selection) AND SQL selection` ?
Therefore I am afraid that we cannot use custom operators as I hoped. It could be possible only with PostgreSQL. Therefore I think we should explicitly provide two objects for queries. One SqlAlchemy object for the selection with simple tags and one to-be-defined object for the selection with list tags. I see two possibilities for representing to-be-defined :

1. A Python function taking a dictionary and returning a boolean
1. A custom object representing the structure of the query with operators combined with AND, OR, etc. It could rely on a syntax very similar to SqlAlchemy.

There is one need that make me favor the second solution (an may compromise the direct use of SqlAlchemy objects for SQL selection) : we will need to save/load these objects next to the pipelines (either in file or in database). But there is no way to save a Python object in a portable way. Pickle is not an option because its format is dependent on the code. For instance, if you change your class names or module organization, your pickled objects can become unreadable. We will have to discuss this point also.

**Comment by sapetnioc** [comment]
I committed the beginning of implementation for filters. Therefore, I added a new mandatory dependency for populse_db : lark-parser

**Comment by sapetnioc** [comment]
In the path of making filters compatible with time and date types, I encountered a problem with lists of time, date or datetime. They are not supported by `ast.literal_eva()l` and therefore cannot be serialized/deserialized into database column. To fix this, I introduced a specific serialization for these list types.

Doing this, I found another problem in query codes (get_path, get_initial_path, filter_path, etc.). To represent a path value, they were all returning directly a row from SqlAlchemy. But with this row, a user cannot access a tag value given the tag name because this tag name is hashed in the database. Therefore, these methods now return `TagRow` instance(s). A `TagRow` is created given a SqlAlchemy row item and takes care of the conversion of the tag name with hash. It also handle the conversion of the values. Therefore, lists tags are returned as Python lists, not as their string serialization.

**Comment by servoz** [comment]
The Pandora's box ...

**Comment by sapetnioc** [comment]
And there is another thing that is coming out of the box : the representation of time, date and datetime values in filter expression. To date, a number is represented as in Python, a string is beetween double quotes and lists are using Python syntax. We have to find a way to identify the other types without ambiguity. I propose not to introduce any keyword but to directly use what `isoformat()` method returns on the datetime.* types. This would give the following :

* **time**  is represented by `<hour>:<minute>:<second>.<microsecond>` with the possibility to omit second and microsecond. For instance, the following would be valid times : `12:54`, `21:53:42`, `4:18:00.000004` (I do not know why `isoformat()` is padding microseconds with 5 zeroes, in this case `4` should be acceptable for us)
* **date** is represented by `<year>-<month>-<day>`. The following would be valid dates : `2018-05-23`, `0001-01-01`. Personally, I would choose tot also accept `2018-5-23` and `1-1-1` (this is not ISO).
* **datetime** is represented by `<date>T<time>`. For instance `2018-05-23T16:46` or `'0001-01-01T00:00:00'`

As long as we do not plan to implement operation using the minus (`-`) or colon (`:`) signs in our filters, I think there is no ambiguities for parsing this syntax.

**Comment by sapetnioc** [comment]
By the way, we did not include `bool` and `list_bool` types in populse_db. Should we do it ?

**Comment by servoz** [comment]
It's OK for me to directly use isoformat() method on datetime.* types. As well, I agree with you that it will be better to follow ISO for date representation.
Concerning the bool and list_bool, except if it is a too big job, I thatit could be a good idea to include that types in populse_db.
