### ISSUE TITLE
Deploy populse_db on PyPI

### ISSUE THREAD

**Issue by ouvrierl** [populse/populse_db#24]
Hi,

I did a lot of work on populse_db these last days, and I wanted to give some details of what has been done:
- First of all, the comments in the source code has been improved
- The documentation has been written with Sphinx
  - It is available here: https://populse.github.io/populse_db/
  - The website is in docs/html/ folder
  - There is a general documentation, a user documentation, and the API generated automatically
- The license CeCILL-B has been put on the repository
- The README.md file has been improved
- CI is now on Travis for Linux and OSX, and on AppVeyor for Windows

Do you think we are ready to deploy it on PyPI?

Best regards

Lucie

**Comment by denisri** [comment]
That's really great !
I just had a quick look at the doc for now, I haven't read it all yet, and I'm less involved in databasing than Yann, so I'll let him make comments from the Neurospin side before we release (he's back from vacation next week). But for me I see no reason why we could not release on Pypi.
Thanks for your work Lucie...

**Comment by ouvrierl** [comment]
Thanks!

And no problem for waiting for Yann's approval

**Comment by sapetnioc** [comment]
Thanks for the documentation effort. Yes, I think we are ready for Pypi.

**Comment by ouvrierl** [comment]
Great!
Maybe we could talk about it more precisely during the meeting next Monday?

**Comment by servoz** [comment]
that's a good idea! I add this point to the agenda for the next monday.

**Comment by sapetnioc** [comment]
I noticed that the Pypi name is `populse-db` whereas the GitHub name is `populse_db`. This is not a big deal but I think it is better to be coherent if possible and change one of the two names. I remember that we decided to use an underscore in a meeting. We can still change our mind (but the Python module would always be with an underscore).

**Comment by ouvrierl** [comment]
With pip, both populse_db and populse-db are working :)
It is just on the PyPi website that populse-db is written (_ must be replaced by -)

**Comment by servoz** [comment]
[Ok ! I didn't know this ... ](https://stackoverflow.com/questions/19097057/pip-e-no-magic-underscore-to-dash-replacement)

**Comment by sapetnioc** [comment]
I did not know either. All is good then.

**Comment by servoz** [comment]
As it was suggested in the last web-meeting, an up to date tuto for the [PyPi deployment recipes is available in the last minutes report](https://github.com/populse/populse.github.io/blob/master/Meeting_minutes_180806.md#-1-deploiement-populse_db) (short and long version !)
