### ISSUE TITLE
few questions ...

### ISSUE THREAD

**Issue by servoz** [populse/populse_db#25]
For populse_db installation from source:
I propose to change (in the tuto):

From source:
sudo apt-get install git
git clone https://github.com/populse/populse_db.git /tmp/populse_db
cd /tmp/populse_db
sudo python setup.py install
cd /tmp
sudo rm -r /tmp/populse_db
python/ directory must be added to $PYTHONPATH if the module is installed from source

to:
From source:
sudo apt-get install git (Ubuntu) or dnf install git (Fedora)
git clone https://github.com/populse/populse_db.git /tmp/populse_db
cd /tmp/populse_db
sudo python3 setup.py install
cd /tmp
sudo rm -r /tmp/populse_db

-> I guess, it is better to use python3, otherwise modules will be installed in the packages installation directory for python 2.x ?
-> I do not need to change the PYTHONPATH to make installation with distutils, but with my linux distrib it is necessary to give the prefix for packages installation directory with python3 (python3 setup.py install --prefix=/usr) and not with python 2.x (It is more a config problem in my station, I guess) !!!

In the python/populse_db/ info.py:
-> The line: brainvisa_build_model = 'pure_python' is a copy and paste error ?
-> So we do PostgreSQL database module installation by default with populse_db ? 
EXTRA_REQUIRES = {
    'postgres': [
        'psycopg2-binary',
    ],
}

**Comment by ouvrierl** [comment]
-> For python or python3, all depends on how python is installed on each computer, and if there are several versions installed. We can put python3 to avoid issues, but I think the users that will use populse_db will at least have basic knowledge of python.

-> I can't really answer this point. David and I had to add python/ directory to PYTHONPATH after having cloned populse_db to make it work

-> Yes it must be a copy/paste error

-> If I understood it well, we use it for the tests so the module must be installed but I can do it in Travis/AppVeyor script directly

**Comment by denisri** [comment]
> -> The line: brainvisa_build_model = 'pure_python' is a copy and paste error ?

You mean, why is this line in info.py ? It's for our build system in brainvisa: it tells it that there is no CMake file in the project because it's all python and does not need compilation, but still allows to integrate with all the other brojects. So, no, it's not a spurious copy/paste error.

> -> So we do PostgreSQL database module installation by default with populse_db ?

I think Postgres should not be a mandatory dependency of populse_db, as it can work with only Sqlite, and postgres is not a really lightweight dependency.

**Comment by sapetnioc** [comment]
> I think Postgres should not be a mandatory dependency of populse_db, as it can work with only Sqlite, and postgres is not a really lightweight dependency.

The dependency is not on PostgreSQL but on psycopg2 which is only a client API for Postgres. It is not so big. I would like to have it optional but, as a `pip` user, I think it makes it difficult when packages have packaging options. First, I do not know a standard way to find the information about existing options. Then, I do not know how to combine these options when several are existing. Last, a user have to know that it must use `pip install populse_db[postgres]` instead of `pip install populse_db` when he needs Postgres. It can be explained in the doc but makes the installation doc a little bit more complex. I prefer to say: "just install with `pip install popule_db`", and it will work in all cases even if a user choose to switch to postgres later. Moreover, these options are specific to Python and may be difficult to port to other packaging systems.

For using python3 in installation instructions I do not know what to say. I wonder when Python 3 will become the default Python in distribution or if `python3` exists on all distribs.

**Comment by denisri** [comment]
If installing the psycopg2 module does not require to install postgresql itself, then I agree. We can try the install on a clean system (using docker) to see if it's OK like that.

**Comment by servoz** [comment]
thanks @denisri !
- In fact I am currently spending some time to read as much as possible all the codes and the stuffs around the populse_db and I confess that I am discovering the Building and Distributing Packages with Setuptools that I have never use  before ! Because the key brainvisa_build_model is not used in the release_info dictionnary of the setup.py file I did not understand why the brainvisa_build_model attribute was defined in the info.py file. So, no problem for me to keep it in the info.py, for the build system in brainvisa !
- +1 for Postgres (but it should be a good idea to develop populse_db to permit use of Postgres ... todolist !)

thanks @ouvrierl !
- I know that I am  annoying and too fussy, but I definitively think that when we write tutorial we have to write like we are dealing with a beginner (expert will go straight to waht he want ... but the beginner will succeds ... and it is cool !). For this reason I propose to try to give installation recipes as robust as possible, so in this case it is not a bad idea to give obvious commands or parameters (who can do more can do less, not the contrary). You have done a very great job for the doc. I just propose few adds or changes to make it as robust as possible  ...

thanks @sapetnioc
 - Ok I totally understand your point of view about the needs to make easy the installation of populse_db (for me it is a key to the success, because if a lambda user do not succeed easily to install and use our projects it not a good start !). Ok for me to install psycopg2 !
- for the python2.x and 3.x: I do not want to say that it is necessarry to change python with python3, but I think that it will be not to bad to precise python # for python 2.x \n python3 # for python 3.x. I am exactly the guy that will make very quick install without really think (i know it is very bad, but i think I am not the only one !) and that will say "this stuff is a shit" because I use later pytnon3 and I raise an ImportError ...

**Comment by sapetnioc** [comment]
I just checked on a brain new Ubuntu 18.04 (via Docker). Using `pip install psycopg2-binary` works without having to install anything (but python-pip of course). The downloaded package is only 2.7 Mb and had no dependency. Therefore, we can safely keep this dependency mandatory.

**Comment by servoz** [comment]
ok for me !

**Comment by denisri** [comment]
OK.

**Comment by ouvrierl** [comment]
Hi!

Populse_db is not compatible with python2 as there are some instructions in the module only working with python3.

I changed python to python3 in the script of installation, and removed the PYTHONPATH sentence.

For psycopg2 module we are not changing anything right?

**Comment by sapetnioc** [comment]
On Mon, Aug 6, 2018 at 9:11 AM Lucie OUVRIER-BUFFET <
notifications@github.com> wrote:

> Hi!
>
> Populse_db is not compatible with python2 as there are some instructions
> in the module only working with python3.
>
Argh ! I missed this the history of populse_db. We have to add this point
to today's meeting because droping Python 2.7 compatibility is not an
option for us.

**Comment by ouvrierl** [comment]
Maybe it will be easy to fix, I am retesting python 2.7 right now on Travis as it's working on my local machine

**Comment by ouvrierl** [comment]
For now I have those mistakes on Travis:
* super(FilterToQuery, self).__init__() => TypeError: super() argument 1 must be type, not classobj
* query = session.__filter_query('collection1', filter) => AttributeError: DatabaseSession instance has no attribute '_TestDatabaseMethods__filter_query'

I will try to fix it as soon as possible

**Comment by denisri** [comment]
Good news! Thanks.
