### ISSUE TITLE
Automatically create missing fields when adding documents ?

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#27]
I almost finished #26 (I am creating tests) and it raises a question. What to do when someone adds a document containing values for fields that were not created ? I see several options :

1. Silently create the field when it is possible to guess its type from the value in the document (e.g. any value except `None` or `[]`). Otherwise raise an exception.
1. Raise an exception.
1. Add an option `create_missing_field` in `add_document` that would choose between the first two behavior. If we choose this option, what would be the default value for `create_missing_field` ?

Personaly, I am in favor of automatically creating the fields by default. Thefore I would choses either option 1 or option 3 with `create_missing_field=True`.

**Comment by servoz** [comment]
I am leaning towards the 1st option "Silently create the field when it is possible to guess its type from the value in the document"
Then I am not against the 3rd option (but in this this case with the default option corresponding to the 1st option :-)))

**Comment by ouvrierl** [comment]
I like the 3rd option best, set to True :)

**Comment by denisri** [comment]
I also prefer option 3 with default to True: in some cases ensuring the database has only the expected fields can be useful I think.

**Comment by servoz** [comment]
So, the die is cast.
