### ISSUE TITLE
FieldRow cannot be used outside a database session context

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#28]
When requesting documents, the API returns a FieldRow object for each document. Internally this object uses a SQLAlchemy row object. But a row cannot be used outside the context of a database session. Therefore, user code cannot use the documents returned by the API. Here is an example of code to reproduce the problem:
```
from populse_db.database import Database

# Create a database and put a document in a test collection
db = Database('sqlite:///:memory:')
with db as dbs:
    dbs.add_collection('test')
    doc = {
        'index': 'test',
        'string': 'string',
        'int': 1,
        'float': 1.4,
        'boolean': True,
        'dict': {
            'string': 'string',
            'int': 1,
            'float': 1.4,
            'boolean': True,
        }
    }
    dbs.add_document('test', doc)

# Create a function that returns the test document
def the_document(db):
    with db as dbs:
        return dbs.get_document('test', 'test')


# Use the function to retrieve the document
doc = the_document(db)

# Try to access a value in the document 
doc.float # Boom !
```

**Comment by sapetnioc** [comment]
I see a possible fix to this problem. First split `get_document()` in two : `__get_document_row()` for code the really needs a SQLAlchemy row and `get_document()` that would build a `FieldRow` after calling `__get_document_row()`. Then change the implementation of `FieldRow` to fully read the SQLAlchemy row on construction and only storing a dictionary with the result. For instance, this class could derive from `dict` and also allow to access to fields via attributes (i.e. `__getattr__()`) for backward compatibility.

**Comment by ouvrierl** [comment]
It seems like a great idea to avoid returning SQLAlchemy objects to the users, if it's not too complicated to do

**Comment by sapetnioc** [comment]
It is almost done. I have some tests that are not working anymore but up to now nothing that cannot be handled.
