### ISSUE TITLE
Filter json type might not be working

### ISSUE THREAD

**Issue by ouvrierl** [populse/populse_db#29]
Hi,

I think filtering json type isn't working properly.
I tried this little script, and I think I do not have the good result from filter_document method.

```
    import os
    import tempfile

    import shutil

    from populse_db.database import Database, FIELD_TYPE_JSON

    # Generating the database in a temp directory
    temp_folder = tempfile.mkdtemp()
    path = os.path.join(temp_folder, "test.db")
    string_engine = 'sqlite:///' + path
    database = Database(string_engine)

    # Creating the session and working with it
    with database as session:

        # Creating a profile table
        session.add_collection("coll")

        # Adding JSON field
        session.add_field("coll", "json", FIELD_TYPE_JSON)

        # Adding documents
        session.add_document("coll", "doc1")
        session.add_document("coll", "doc2")
        value = {}
        value["key"] = "value"
        session.add_value("coll", "doc1", "json", value)

       # Filter
        filter = "{json} == \"{'key': 'value'}\""
        result = session.filter_documents("coll", filter)
        for document in result:
            print(document)
        # Nothing is returned, but doc1 should be

    shutil.rmtree(temp_folder)
```

Maybe the problem is that we use {<field>} for the fields in the parser, should we change the syntax to avoid clashes with json values?

**Comment by ouvrierl** [comment]
I tried filter = "{json} == \"{\"key\": \"value\"}\"" instead of filter = "{json} == \"{'key': 'value'}\"", but I get this error:

/usr/bin/python3.6 /home/lucie/Documents/populse_db/python/populse_db/little_test.py
Traceback (most recent call last):
  File "/home/lucie/Documents/populse_db/python/populse_db/little_test.py", line 41, in <module>
    for document in result:
  File "/home/lucie/Documents/populse_db/python/populse_db/database.py", line 1500, in filter_documents
    filter_query = self.__filter_query(collection, filter_query)
  File "/home/lucie/Documents/populse_db/python/populse_db/database.py", line 1473, in __filter_query
    tree = populse_db.filter.filter_parser().parse(filter)
  File "/usr/local/lib/python3.6/dist-packages/lark/lark.py", line 197, in parse
    return self.parser.parse(text)
  File "/usr/local/lib/python3.6/dist-packages/lark/parser_frontends.py", line 137, in parse
    return self.parser.parse(text)
  File "/usr/local/lib/python3.6/dist-packages/lark/parsers/xearley.py", line 126, in parse
    column = scan(i, column)
  File "/usr/local/lib/python3.6/dist-packages/lark/parsers/xearley.py", line 115, in scan
    raise UnexpectedInput(stream, i, text_line, text_column, {item.expect for item in to_scan}, set(to_scan))
lark.lexer.UnexpectedInput: No token defined for: 'k' in 'key":' at line 1 col 13

Expecting: {'BOOLEAN_OPERATOR'}

**Comment by sapetnioc** [comment]
Now, there is a syntax difficulty to represent a string with a double quote in it. I hope that the grammar accepts the string `"{\"key\": \"value\"}"`. But this string must be escaped to be in a Python literal. There are several way to represent strings in Python. Here is three Python syntax for this string (all three represent exactly the same string) : `r'"{\"key\": \"value\"}"'`, `'"{\\"key\\": \\"value\\"}"'`, "\"{\\\"key\\\": \\\"value\\\"}\"'. Personally I would use the first one that is more readable.

**Comment by ouvrierl** [comment]
Thanks!
It's working with that: filter = "{json} == \"{\\\"key\\\": \\\"value\\\"}\""
Sorry I didn't know the precise syntax
