### ISSUE TITLE
Do not print test name when executing tests

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#30]
There is a standard way to produce the output of tests and printing the test names makes the output not as expected. Personally, I launch tests with `python -m populse_db.test`. If I want more detail on what is going on (or if I want to stop on first error), it is possible to give options to the command. For instance, `python -m populse_db.test -v` allow to see the name of the test being executed. See `python -m populse_db.test -h` for possible options.

**Comment by ouvrierl** [comment]
Oh I didn't know this option that's cool, I will remove the print!
