### ISSUE TITLE
Allow document identifier to be composed of several fields

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#31]
To date when creating a collection, a string must be given in order to identify which single field is a unique document identifier. Technically, this field becomes a single column primary key of a SQL table. Therefore, it is no possible to store two documents with the same value in this field. But there are use cases where it is better to have several columns to identify a single document. For instance in a `software` collection, one could want to store software properties for several version of the same software. In this collection, a single software document would be identified by two fields, for instance `name` and `version`.

I propose to change the API to allow to use several values whenever document identification is involved. Methods that requires a single string would also accept a `tuple` or a `list` when several values are necessary to identify a document.

The change may not be entirely backward compatible. When inspecting a collection, we get an item named `primary_key` that is a string. I propose to change it to `primary_keys` that would always be a list or tuple.

**Comment by servoz** [comment]
Is it really necessary to use the document identifier (primary key) when dealing with a collection ? If we have a software 'toto' with version 1.0 and 2.0, we can imagine for the collection 'softwares',  a document with the field 'soft' = 'toto' and a field 'ver' = 1.0 and a second document with the field 'soft' = 'toto' and a field 'ver' = 2.0. By using querying with the two field it is not doing the job ? I guess I miss something !

**Comment by sapetnioc** [comment]
The current API makes it mandatory to have a primary key that is a single column of type `string`. What I need is to allow to use several columns. It would be even better if these columns could have different types. But I agree that we could make the primary key optional. Note, that without primary_key defined some methods such as `get_document(collection, primary_key_value)` could not work.

**Comment by sapetnioc** [comment]
I have a new API change proposal :

1. Make the primary_key optional on collection creation. We could remove the possibility to create a primary key at this point (see below) but we could choose to keep it for backward compatibility.
1. Create a new method `set_primary_key(first_field_name, *other_field_names)` that would accept one or more field names to define a primary key. With this, it would be possible to use fields that are not strings in primary keys.
1. Methods that need to identify a single document would always accept a tuple with one or more values (as many as primary key fields). API would also accepts single values of simple types (`str`, `int`, `float`, etc.) instead of a tuple with a single value. For instance, `'document_id'` would be equivalent to `('document_id',)`.
1. Change the attribute `primary_key` of a collection (which is a string) to `primary_keys` (which would be a tuple)

**Comment by servoz** [comment]
Ok for me.
