### ISSUE TITLE
improve selection and performance

### ISSUE THREAD

**Issue by denisri** [populse/populse_db#42]
In the current API of populse_db 2.0 I don't find all the selection features we would need:
* we have a `DatabaseSession.get_document()` method, and a `filter_documents()` method, which allow to get rows in the database, each wrapped in a python object. Complete rows are extracted for every selected document (all fields, possibly converted with some processing, especially for list values).
* we have a `DatabaseSession.get_value()` method, which gets a single field of a single document. This method is currently implemented using `get_document()` which builds a complete row object, then extracts the needed field and returns it, which is far from optimal.
* the low-level sqlite engine object also has a `get_value()` method, which is not used by the `DatabaseSession.get_value()` method, and which does not perform object conversion (lists...)

We would need to
* improve the performance of `DatabaseSession.get_value()` to avoid retreiving/building full documents with all fields values converted if we don't need them. The presence of lists in some fields we don't need here is likely to heavily slow things down.
* have a selection method which gets only a list of expected fields, not converting the remaining ones. This could be a method like `DatabaseSession.filter_values(collection, filter_query, fields_list)` and perhaps an easier variant `get_values(collection, document_id, fields_list)`

* I also see that the sqlite implementation of `set_values()` performs one SQL request for each field value, whereas I think it could do all fields with a single request, selecting the document only once, but this is probably less critical and easy to fix.

**Comment by sapetnioc** [comment]
I already made some optimization of `set_values` by using SQlite `executemany` method instead of a loop on data for the same SQL query. But you are right, we could collect all the values to modify on the main table and perform a single query at the end to set them all.

For field selection, I think we could keep the same API and add an optional parameter `fields` to select the fields we are interested in. The selection part is easy to implement. The difficulty here is for the returned object. To date it is a class that is generated for each collection and containing all field names (therefore, there is no need to store field names for each document). If there is a field selection, we would need to return a kind of improved dict for each row (including field names). To even make things faster on cases user do not need field names, we may also add another optional boolean parameter `as_list` for only returning a list of values when `True`.

**Comment by denisri** [comment]
For `set_values` I have also done a slight modif to perform a single request.
For selection, I quite agree on the idea of adding an optional parameter `fields`, but as you mention it the returned value type would perhaps depend on parameters. Maybe the `as_list` is the best option. Either that, or just decide that if `fields` is specified, then the returned object is a list of fields values, in the same order as the `fields` parameter.

**Comment by sapetnioc** [comment]
Congratulation for your effort in understanding the populse_db machinery.

I think it is fairly easy to add both options. In all case the result of a database query is a kind of row. To date the returned object for documents is a mix between `dict` and `list`. Its items can be accessed both by field name or by index in the row. If `fields` is present we may just return a dedicated object to have the same behavior. This would be coherent with the existing API. And yes, if `as_list` is `True`, we would return a list with exactly one element per selected field. If `fields` is `None`, this would select values corresponding to the fields returned by `get_fileds`/`get_fields_names`.

**Comment by denisri** [comment]
OK (if this object is lightweight enough but I don't think the bottlenecks are here).

**Comment by denisri** [comment]
Now that output_directory has been set to `derived_data`, there is a discrepency in MIA processes output file names (still in `raw_data`) and `output_directory`. Maybe because of that (?), the `spatial_preprocessing_1` pipeline now fails: I can't find the `normalize12_2` process output `normalized_files` (`wralej170316-IRMFonct.+perfusion-2016-03-17083444-1-BOLD_CVR_7_53sl_ModeratePNSSENSE-FEEPI-001212.000.nii`) and the next process, `smooth1`, fails because it lacks its input.

**Comment by servoz** [comment]
Yes, I noticed this discrepancy.
I am trying to fix this issue.
I am currently reading and understanding the new way of working, and it is taking me some time.
I'm starting to understand better how it works and I hope to be able to make the changes ASAP (the code in the mia_processes bricks is no longer suitable,  I think) ...

**Comment by denisri** [comment]
Or maybe I have done something wrong but I don't know what yet, because all other outputs seem to go in `raw_data` as they used to, only this one is missing after an apparently successful run of `normalize12`.

**Comment by denisri** [comment]
It's strange because in the same pipeline, there are 2 instances of the same process, `normalize12_1` and `normalize12_2`, and the 1st one has correctly produced its output, whereas the second has not. I'll retry from scratch using a new project after reimporting the raw data: maybe something got wrong in my data (I am re-running many times all kinds of processings on them for several days).

**Comment by servoz** [comment]
in any case, it doesn't hurt me to immerse myself in the capsulEngine machinery ...

**Comment by denisri** [comment]
Uh oh I just realize that I'm replying in the wrong ticket for more than an hour... I must be tired... This should be in populse/populse_mia#180.

**Comment by servoz** [comment]
:)

**Comment by sapetnioc** [comment]
Ok, its done for the implementation. There is some documentation still missing.
