### ISSUE TITLE
why do we impose lark version < 0.8

### ISSUE THREAD

**Issue by denisri** [populse/populse_db#51]
I notice that in casa-distro images 5.0/5.1 we install lark-parser (via `pip`) using the constraint `lark-parser>=0.7,<0.8`.
In 5.3 (ubuntu 22.04) I did not pay attention to the `<0.8` part and installed it using `apt`, which actually installs lark-parser version 1.1.1.
This makes populse_db tests fail with the following error:
```
Traceback (most recent call last):
  File "/casa/host/src/populse/populse_db/master/python/populse_db/test.py", line 1885, in test_filter_literals
    self.assertEqual(value, expected_value)
AssertionError: Lists differ: [None] != []

First list contains 1 additional elements.
First extra element 0:
None

- [None]
+ []
```
I can of course reinstall `lark-parser<0.8` using pip, which fixes the test, but as we are thus relying on an obsolete version, I was wondering if we should change populse_db in the future (in which way?), or be stuck with an obsolete parser ?

**Comment by sapetnioc** [comment]
I think this had been fixed in v3. But the database engine had been rewritten (I discovered JSON management functions in SQlite) so there is no easy backport.

**Comment by sapetnioc** [comment]
Oh yes, the dependency had been `>=0.7.0` for years. So I suspect an incompatible change in Lark after the last modification on master.

**Comment by sapetnioc** [comment]
I think I had this problem in v3. I see a modification in the v3 grammar, introducing an `empty-list`. I will see if backporting this fixes the issue.

**Comment by sapetnioc** [comment]
`lark-parser` had become `lark` on Pypi.

**Comment by denisri** [comment]
> Note that on Pypi, [latest lark-parser version](https://pypi.org/project/lark-parser/#history) is 0.12 but there are more recent [tags on Github](https://github.com/lark-parser/lark/tags). This is why we did not see any error in tests (0.12 is ok).

I think it's just because our images install actually specify `lark-parser<0.8`. Now in 5.3 images the system lark (apt) is installed, and it's a newer version, so we get the problem.
Anyway your fix works, thanks a lot ! :)

**Comment by denisri** [comment]
Let's say yes as it simplifies things for us and pip can still install it.
I don't know if there is a syntax to say "I depend on either lark-parser>=0.7 or lark" ?

**Comment by servoz** [comment]
I think it's not an option because the V2 tests (master) are failing now with python2.7 ...

**Comment by sapetnioc** [comment]
Lark dropped Python 2 support on 1.0.0. Therefore, I changed dependency for v2 to `lark<1.0.0`.

**Comment by servoz** [comment]
cool ! Thanks @sapetnioc.
 I thinks this ticket can be closed now ? I love this reactivity :-))
![Screenshot from 2022-06-20 15-43-59](https://user-images.githubusercontent.com/37933899/174615247-668c444c-be76-4c95-9fb4-a1f4f4ada399.png)
)

**Comment by denisri** [comment]
OK then.

**Comment by servoz** [comment]
we can drop python2 only from V3 ?

**Comment by servoz** [comment]
> And is there a lark<1.0 or was it lark-parser, before 1.0 ?

[it seems that lark is taking over the releases of lark-parser, from 0.10.1](https://pypi.org/project/lark/#history)
