### ISSUE TITLE
Problems with transactions

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#8]
Transactions are an important feature of the database. There is a problem with SqlAlchemy and some commands (such as table creation) that automatically commit all changes done in a transaction (at least with SQLite). This is also the case by default when using directly ``sqlite3`` but it can be customized at connection creation to support all commands in transactions (using ``isolation_level=None``).

I am trying to find a workaround to ask to SqlAlchemy to use this feature of SQLite but failed so far. If it is not possible, we may have to drop usage of SqlAlchemy. This coud be done by keeping most (maybe all) the current API of popuse_db. But does someone is using directly SqlAlchemy with a populse_db database in user code ?

I am still investigating to find a solution to this problem while keeping SqlAlchemy.

**Comment by sapetnioc** [comment]
Ok, I found a [workaround documented in SqlAlchemy SQlite backend](http://docs.sqlalchemy.org/en/latest/dialects/sqlite.html#serializable-isolation-savepoints-transactional-ddl). We can keep SqlAlchemy then. Here is a code sample that creates a table in a transaction :
```
from __future__ import print_function

import os

import sqlite3
from sqlalchemy import create_engine, event
from sqlalchemy.orm import sessionmaker

# Starts without database
db = '/tmp/test.sqlite'
if os.path.exists(db):
    os.remove(db)


engine = create_engine('sqlite:///%s' % db)
@event.listens_for(engine, "connect")
def do_connect(dbapi_connection, connection_record):
    # disable pysqlite's emitting of the BEGIN statement entirely.
    # also stops it from emitting COMMIT before any DDL.
    dbapi_connection.isolation_level = None

@event.listens_for(engine, "begin")
def do_begin(conn):
    # emit our own BEGIN
    conn.execute("BEGIN")

Session = sessionmaker(bind=engine)
session = Session()
session.execute('CREATE TABLE user (id);')
# Rollback must cancel table creation
# Commit must put table in database
session.rollback()


# Check with Sqlite that table user exists
# It is expected to have an error here if
# rollback() was used an nothing if commit()
# was used
db = sqlite3.connect(db, isolation_level=None)
c = db.cursor()
c.execute('SELECT * FROM user;')
```

**Comment by sapetnioc** [comment]
Now that we know that we can handle transactions, we must define an API to allow users to manage transactions. In SqlAlchemy, transactions are managed by a session object. You can perform as many database actions on a session object and, at the end, you either commit the changes or rollback to revert the database to the state it had upon session creation.

I propose to expose the session management in populse_db with the following API :
```
from populse_db import Database

db = Database('sqlite:////tmp/test.sqlite')
with db as session:
    session.add_tag(...)
    session.set_value(...)
```

Here is a sample code that illustrate how to implement this API and show that it works in case of exception in user code (table creation is rolled back).
```
from __future__ import print_function

import os
import sqlite3

from sqlalchemy import create_engine, MetaData, event
from sqlalchemy.orm import sessionmaker

        
class Database(object):
    def __init__(self, url):
        self.engine = create_engine(url)
        self.metadata = MetaData(bind=self.engine)
        
        @event.listens_for(self.engine, "connect")
        def do_connect(dbapi_connection, connection_record):
            # disable pysqlite's emitting of the BEGIN statement entirely.
            # also stops it from emitting COMMIT before any DDL.
            dbapi_connection.isolation_level = None
        
        @event.listens_for(self.engine, "begin")
        def do_begin(conn):
            # emit our own BEGIN
            conn.execute("BEGIN")
        self.session_maker = sessionmaker(bind=self.engine)

    def __enter__(self):
        self.session = self.session_maker()
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        self.session = None

    def commit(self):
        self.session.commit()
        
    def rollback(self):
        self.session.rollback()
    
    
    def execute(self, sql):
        self.session.execute(sql)
    

# Starts without database
db = '/tmp/test.sqlite'
if os.path.exists(db):
    os.remove(db)
    
database = Database('sqlite:///%s' % db)
try:
    with database as session:
        session.execute('CREATE TABLE user (id)')
        BOOM # raises an error
except Exception as e:
    print(e)

# Check with Sqlite that table user exists
# It is expected to have an error here if
# rollback() was used an nothing if commit()
# was used
db = sqlite3.connect(db, isolation_level=None)
c = db.cursor()
c.execute('SELECT * FROM user;')
```

**Comment by ouvrierl** [comment]
Hi, I just saw the issue now, sorry.
I also worked on this issue, and this is where I am at now:
- I can now do every action in sessions (transactions)
    - For creating tables, I am doing it this way:

                tag_table_current = Table(tag_name + "_current", self.metadata,
                                          Column("index", Integer,
                                                 primary_key=True),
                                          Column("order", Integer,
                                                 primary_key=True),
                                          Column("value",
                                                 self.tag_type_to_column_type(
                                                     tag_type),
                                                 nullable=False),
                                          ForeignKeyConstraint(["index"],
                                                               ["path.index"],
                                                               ondelete="CASCADE",
                                                               onupdate="CASCADE"))
                tag_table_initial = Table(tag_name + "_initial", self.metadata,
                                          Column("index", Integer,
                                                 primary_key=True),
                                          Column("order", Integer,
                                                 primary_key=True),
                                          Column("value",
                                                 self.tag_type_to_column_type(
                                                     tag_type),
                                                 nullable=False),
                                          ForeignKeyConstraint(["index"],
                                                               ["path.index"],
                                                               ondelete="CASCADE",
                                                               onupdate="CASCADE"))

                # Both tables added (0.03 sec on average)
                current_query = CreateTable(tag_table_current)
                initial_query = CreateTable(tag_table_initial)

    - Thanks to CreateTable (in sqlalchemy.schema), I can have the sql request corresponding to the table very easily, and can execute it in the session.
- I do not use a temporary folder anymore, I am working directly on the original file
- For the session management:
    - I create a session at the database opening in the constructor, and it can be accessed via self.session
    - I have a method called save_modifications, that commits the session, and a method called unsave_modifications, that rollbacks the session

Can we consider the issue closed, or you still see some source code to improve?

**Comment by sapetnioc** [comment]
Using SQL for table creation in my example was only to make the example shorter. The content of the table was not important there. In this example the ``execute()`` method was here to represent all methods It is better to keep the SqlAlchemy way as you did.

I believe that it is better to let the user manage the session creation and termination. In your model, the session has exactly the same life span as the Database. But we may create a database and start a session later. We could also need to have several sessions on a database or even use nested sessions. I have real use cases in mind such as using database in web servers that are sometimes multi-threaded (database connections cannot always be shared across threads) but I did not want to make this topic too complex.

The user API I propose gives the user the responsibility to choose when and how a new session is created and ended (using the ``with`` block). The implementation I proposed is rather simple and does not allow to handle complex cases (because there is still a single ``self.session`` in Database object as you chose). But leave the possibility to improve the implementation later without touching the user API.

**Comment by ouvrierl** [comment]
I totally get your point and it's a good idea, but each function of the API modifying the database would need the session as parameter in this case or am I missing something?

**Comment by sapetnioc** [comment]
No, they would use ``self.session`` to access the database. The difference
is that self.session is created by ``__enter__()`` and deleted (set to
``Ǹone```in fact) in ``__exit__()``. So the only difference woul be that
using a Database method outside the ``with`` block would raise an error.
Without further improvement, the error message would be cryptic (such as
"None type has no attribute..."). But we can improve that later by changing
``self.session`` into a property (i.e ``self.session`` would become a
method call) that raises a user friendly error when the session is not
created.

**Comment by ouvrierl** [comment]
Thanks for the details, I will look at it.

**Comment by ouvrierl** [comment]
Should we start improving the transactions now or the API still needs improvements?

**Comment by sapetnioc** [comment]
Yes, I think we are ready. If I remember what we discussed earlier, I should do the first move on this.

**Comment by ouvrierl** [comment]
Yes if you can, I could do it but I'm not sure I precisely understood how you wanted to do it.

**Comment by sapetnioc** [comment]
I reopened this issue because I made an implementation but I would like to discuss two choices I did about recursive calls and thread safety.

In the new API, we can do almost nothing with a `Database` object except creating a `DatabaseSession` instance with the following code (this is the `DatabaseSession` that has all the useful methods):
```
with database as session:
    session.add_document(...)
```
If the with block terminate with an exception, the session is rolled-back otherwise it is commited. I still have to implement the trick I presented earlier to make table creation (e.g. `add_collection`) support transactions. This will not change the API.

The first choice I did is to allow creating recursive sessions but only the outermost `with` will create a new session object and manage the transaction. All inner `with` statement will reuse the same session and there is no commit nor rollback at the end of these `with` block. For instance, in the following code, `session_out` and `session_in` are the same object :
```
with database as session_out:
    with database as session_in:
       # No automatic commit nor rollback for session_in
    # session_out is commited or rolled back
```
Recursive `with` will not be used directly but may happen if a client function (let's call it `create_items()`) that need a session have to call another function (`create_item()`) that also need a session and may be called independently (without passing an existing session). Both functions would have a  `with` statement but if there is always a commit at the end of a `with` (and therefore in `create_item()`), the `create_items()` function could not be used in a transaction.

The second choice I did is to make the API thread safe. This is a good idea because if we want to use populse_db in a web service, it is common in popular Python web framewok (such as flask or Pyramid) to create a new thread for each request. This is transparent in the API, the `with` statement will automatically create a new session object in each thread. The problem is that my current implementation is not keeping any state data in the database object. For instance, all database model importation (`self.metadata`, `self.table_classes`, etc.) are recreated on each sessions. This is the same for the caches when they are used. I think a user would expect that these values are stored and updated in the database object because the overhead for creating a session is currently important. This can be improved later without touching the API by moving some elements from `DatabaseSession` to `Database` and protect their modification with a lock.

**Comment by servoz** [comment]
the first choice is already wrote, and the second requires again some work, isn't it ?

**Comment by ouvrierl** [comment]
The new API seems great, I was able to use it in MIA thanks to __enter__ and __exit__ methods.

Tables creations are done in sessions like everything else, what problem does it cause in transactions?

**Comment by sapetnioc** [comment]
Both recursion and thread safety are implemented but, you are right, the second point would need optimization.

**Comment by sapetnioc** [comment]
You are right @ouvrierl, the API is fully functional. But one have to know that, to date, session creation can be slow. For instance, in the following code only reading the database, the cache would be created two times (for `session1` and `session2`):
```
database = Database('sqlite:////tmp/test.sqlite', caches=True)
with database as session1:
   ...
with database as session2:
   ...
```

This may become a problem in a context of a program creating a database and often doing small independent requests (yes, I always have web services in mind but not only). In that case, the overhead of session creation as compared to request speed can be very important. But I guess this is not yet a problem for the kind of user code we use and we may address this question later without touching the API.

**Comment by sapetnioc** [comment]
I think we can close this issue now since there are no more problem with transactions (even when creating/deletion tables). We may add another issue when we decide to optimize the session creation time.
