### ISSUE TITLE
Issues with Python 3.6

### ISSUE THREAD

**Issue by sapetnioc** [populse/populse_db#9]
I noticed that tests were failing in Python 3.6 this morning. I believe that there is a difference in the result of database access returned by SqlAlchemy but was not able to investigate. Now all tests are broken on master so I let the ongoing modifications being finished before starting to investigate.

By the way, I improved my knowledge on TravisCI behavior and I believe it is not too complicated to replicate one of the TravisCI build environments within Docker. This would make it possible to fix code locally using the same build as TravisCI (for instance testing with Python 3.6 whereas it is not installed on the developer system).

**Comment by ouvrierl** [comment]
Sorry for the tests, I know they are falling because I changed the way I manage errors in the methods, I will fix it.

**Comment by sapetnioc** [comment]
No problem. My message was just to raise your attention that something may be different in Python 3.6. Take your time to make your changes. We are not in production yet, tests are allowed to fail.

**Comment by ouvrierl** [comment]
It's not a problem with python3.6, the tests fail everywhere because I changed the way the methods are returning. I have to rewrite the tests

**Comment by ouvrierl** [comment]
Ok I will check that next week.

**Comment by ouvrierl** [comment]
There is effectively a problem with python3.6
With other versions of python, when I update the schema with alter table add column or create table statements, the metadata associated to the database is automatically updated so I can have the new schema.
With python3.6, the metadata isn't updated so I would have to commit to have the changes in the metadata.
I already spent a lot of time trying to fix that and didn't find a solution to get the new schema without committing.
For now we decided to only work with python3.5 as it's working well.
Should we make this a priority?

**Comment by sapetnioc** [comment]
I think the main priority is to have a stable API on which we can start to
build tools. But we must also take into account that Python 3.6 will have
to be supported in the future. So if we can anticipate that we will not
have to change the user API to fix issues in Python 3.6, I would say that
we can leave fixing the implementation for later.

**Comment by servoz** [comment]
I totally agree with it.

We have highlighted some weakness (Python 3.6, running time, etc.) that we will must to fix or improve, but for now I think the top priority is to make the connexion between the pipeline part and the database ...

We will start to work on this veru important side next monday !!!!! yahooooooo

**Comment by sapetnioc** [comment]
I will remove the test on Python 3.6 until we find a solution for this issue.

**Comment by sapetnioc** [comment]
Oh, sorry I did not know. The only reason why I removed 3.6 is to have a
shortcut to see if a commit is breaking tests on other versions. So, if you
need it I will put tests on 3.6 back at once.

**Comment by ouvrierl** [comment]
No worries, I still have it on my computer so I can test correctly, I will reput it once the issue is fixed
